baseURL = "https://ddzero2c.github.io"
languageCode = "en-us"
title = "Ryder's Tech Blog"
theme="cactus"
copyright = "© ryder hsu"
googleAnalytics = "G-4TCT5YQLEV"


[params]
colortheme = "white"
showAllPostsOnHomePage = false
postsOnHomePage = 5
tagsOverview = true
rss = true
mathjax = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Subscribe"
url = "/index.xml"
weight = 4

[[params.social]]
name = "github"
link = "https://github.com/ddzero2c"
[[params.social]]
name = "email"
link = "ddzero2c@gmail.com"  # no need for "mailto:" in the head
